packages:
  - packages/*
  - apps/*

catalog:
  '@types/node': ^24.7.0
  '@vitest/coverage-istanbul': ^3.2.4
  better-auth: ^1.3.27
  eslint: ^9.37.0
  typescript: ~5.9.3
  vite: ^7.1.9
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  wrangler: ^4.42.1
  zod: ^4.1.11

minimumReleaseAge: 2880

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - msw
  - sharp
  - workerd

overrides:
  '@conduit8/core': link:../../Library/pnpm/global/5/node_modules/@conduit8/core
