packages:
  - packages/*
  - apps/*
  - backend/packages/*

catalog:
  '@types/node': ^24.9.2
  '@vitest/coverage-istanbul': ^3.2.4
  better-auth: ^1.3.27
  eslint: ^9.39.0
  typescript: ~5.9.3
  vite: ^7.1.9
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  wrangler: ^4.45.3
  zod: ^4.1.12

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@conduit8/core'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - esbuild
  - msw
  - sharp
  - workerd
