name: Release Platform

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/platform-v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Extract version from tag
        id: version
        run: |
          TAG_REF="${{ github.event.workflow_run.head_branch }}"
          VERSION=${TAG_REF#refs/tags/platform-v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Releasing version: $VERSION"

      - name: Extract changelog for this version
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          # Extract the section for this version from CHANGELOG.md
          # Find the line with [VERSION] and read until the next ## or end of file
          CHANGELOG=$(awk "/^## \[$VERSION\]/{flag=1; next} /^## \[/{flag=0} flag" CHANGELOG.md)

          if [ -z "$CHANGELOG" ]; then
            echo "ERROR: No changelog entry found for version $VERSION in CHANGELOG.md"
            echo ""
            echo "Please add a changelog entry for version $VERSION before releasing."
            echo "Example:"
            echo ""
            echo "## [$VERSION] - $(date +%Y-%m-%d)"
            echo ""
            echo "### Added"
            echo "- Feature description"
            echo ""
            exit 1
          fi

          # Save to file for multiline output
          echo "$CHANGELOG" > /tmp/changelog.txt

          # Set output using delimiter
          {
            echo 'notes<<EOF'
            cat /tmp/changelog.txt
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: platform-v${{ steps.version.outputs.version }}
          name: Platform v${{ steps.version.outputs.version }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
